# .github/release.yml

changelog:
    categories:
        - title: 🆙 nightly build
          labels:
              - nightly build
        - title: 👒 Dependencies
          labels:
              - dependencies
        - title: 🏕 Features
          labels:
              - "*"
          exclude:
              labels:
                  - dependencies
