# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Bump up version code"
  lane :bump_up_version_code do
    sh "git switch main"
    previous_version_code = android_get_version_code(
        gradle_file: "app/build.gradle.kts"
    ).to_i
    version_name = android_get_version_name(
        gradle_file: "app/build.gradle.kts"
    )
    version = version_name.split(".")
    major_version = version[0].to_i * 100000
    minor_version = version[1].to_i * 10000
    patch_version = version[2].to_i * 1000
    current_version = major_version + minor_version + patch_version
    pre_release_version = previous_version_code - current_version

    add_git_tag(
        tag: "v#{version_name}-#{pre_release_version}",
    )
    push_git_tags

    new_version_code = android_set_version_code(
        gradle_file: "app/build.gradle.kts"
    ).to_i
    new_pre_release_version = new_version_code - current_version
    branch = "#{version_name}-#{new_pre_release_version}"

    sh "git switch -c night-release/#{branch}"
    git_commit(
        path: ["app/build.gradle.kts"],
        message: ":up: Version Bump #{branch}"
    )
    push_to_git_remote(
        set_upstream: true
    )
  end
end
