name: TEST

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
       actions: write
       contents: write
       statuses: write

    env:
      GH_TOKN: ${{ secrets.GITHUB_TOKEN }}
      WORK_FLOW_FILE: ci.yml

    steps:
      - uses: actions/checkout@v4

      - name: Get run id
        id: run-id-selector
        run: |
          id=$(gh api \
               repos/${{ github.repository }}/actions/workflows/${{ env.WORK_FLOW_FILE }}/runs \
               | jq -r '[.workflow_runs[] | select(.head_branch == "${{ github.ref_name }}").id][0]')
          echo "id=$id" >> "$GITHUB_OUTPUT"

      - name: Get sha
        id: sha-selector
        run: |
          sha=$(gh api \
                repos/${{ github.repository }}/actions/workflows/${{ env.WORK_FLOW_FILE }}/runs \
                | jq -r '[.workflow_runs[] | select(.head_branch == "${{ github.ref_name }}").head_sha][0]')
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Get target url
        id: target-url-selector
        run: |
          url=$(gh api \
                repos/${{ github.repository }}/actions/runs/${{ steps.run-id-selector.outputs.id }}
               | jq -r '.html_url')
          echo "url=$url" >> "$GITHUB_OUTPUT"

      - name: Create a commit status
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/${{ steps.sha-selector.outputs.sha }} \
            -f state='${{ job.status }}' \
            -f target_url='${{ steps.target-url-selector.outputs.url }}' \
            -f description='${{ job.status }}' \
            -f context='TEST (Manual)'
