name: Android CI

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches:
            - main
        paths-ignore:
            - "**.md"

    pull_request:
        branches:
            - main
        paths-ignore:
            - "**.md"

    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        timeout-minutes: 15

        permissions:
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: gradle

            - uses: actions/cache@v4
              with:
                path: |
                  ~/.gradle/caches
                  ~/.gradle/wrappe
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: |
                    ${{ runner.os }}-gradle-

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Run test
              run: ./gradlew test

            - name: Create report
              run: ./gradlew koverXmlReportDebug

            - name: Run octocov
              uses: k1LoW/octocov-action@v1

            - name: Build with Gradle
              run: ./gradlew assembleDebug

            - name: Disp step summary
              if: ${{ always() }}
              run: |
                ${{ toJson(github.event) }} > event.json
                event=$(cat event.json)
                echo "## JOBS_SUMMARY "${{ job.status == 'success' && ':tada:' || ':x:' }}"" >> $GITHUB_STEP_SUMMARY
                echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
                echo "<details><summary>context event details</summary>" >> $GITHUB_STEP_SUMMARY
                echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
                echo "$event" >> $GITHUB_STEP_SUMMARY
                echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
                echo "</details>" >> $GITHUB_STEP_SUMMARY
                echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
