name: Android CI

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches:
            - main
        paths-ignore:
            - "**.md"

    pull_request:
        branches:
            - main
        paths-ignore:
            - "**.md"

    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        timeout-minutes: 15

        permissions:
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up report name
              id: report-name-selector
              run: |
                today=$(date "+%Y%m%d")
                version_name=$(grep "versionName" ${{ github.workspace }}/app/build.gradle.kts | sed "s/ //g" | sed "s/versionName=//g" | sed "s/\"//g")
                version_code=$(grep "versionCode" ${{ github.workspace }}/app/build.gradle.kts | sed "s/ //g" | sed "s/versionCode=//g" | sed "s/\"//g")
                major_version=$(echo $version_name | awk -F "." '{print $1}')
                minor_version=$(echo $version_name | awk -F "." '{print $2}')
                patch_version=$(echo $version_name | awk -F "." '{print $3}')
                current_version=$((major_version * 100000 + minor_version * 10000 + patch_version * 1000))
                pre_release_version=$((version_code - current_version))
                echo "name=report-$today-v$version_name-$pre_release_version" >> "$GITHUB_OUTPUT"

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: gradle

            - uses: actions/cache@v4
              with:
                path: |
                  ~/.gradle/caches
                  ~/.gradle/wrappe
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: |
                    ${{ runner.os }}-gradle-

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            # - name: Run test
            #   run: ./gradlew test

            - name: Create report
              run: ./gradlew koverXmlReportDebug

            # - name: Run octocov
            #   uses: k1LoW/octocov-action@v1

            # - name: Build with Gradle
            #   run: ./gradlew assembleDebug

            - uses: actions/upload-artifact@v4
              with:
                name: ${{ steps.report-name-selector.outputs.name }}
                path: ${{ github.workspace }}/app/build/reports/kover/reportDebug.xml

            - name: Disp step summary
              if: ${{ always() }}
              run: |
                echo "## JOBS_SUMMARY "${{ job.status == 'success' && ':tada:' || ':x:' }}"" >> $GITHUB_STEP_SUMMARY
                echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
                echo "| Step | Outcome | Remarks |" >> $GITHUB_STEP_SUMMARY
                echo "|------|---------|---------|" >> $GITHUB_STEP_SUMMARY
                echo "|Set up report name|\`${{ steps.report-name-selector.outcome }}\`|\`${{ steps.report-name-selector.outputs.name }}\`|" >> $GITHUB_STEP_SUMMARY
