name: Release

on:
    workflow_call:
        inputs:
            tag:
                required: true
                type: string
            pr:
                required: true
                type: string
        secrets:
            token:
                required: true
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        timeout-minutes: 20
        permissions:
            contents: write
            pull-requests: write

        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"
                  cache: gradle

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Build with Gradle
              run: ./gradlew assembleDebug

            - name: Create Releases
              id: create-releases
              run: |
                   tar -czf artifact-${{ inputs.tag }}.tar.gz -C \
                   ${{ github.workspace }}/app/build/outputs/apk/debug .

            - name: Create release
              id: create-release
              run: |
                release=$(gh release create ${{ inputs.tag }} ${{ github.workspace }}/artifact-${{ inputs.tag }}.tar.gz --generate-notes)
                echo "release=$release" >> "$GITHUB_OUTPUT"
